### ISSUE TITLE
Reuse existing cart?

### ISSUE THREAD

**Issue by KevinSleegers** [mike182uk/cart#19]
Hi,

I've only just found out about this great Shopping Cart.
So far it is working great, however I am unable to re-use an existing cart (after refresh).

What do I have to do / check to get an already existing cart (that I know the id of)?
At the moment I am using the following in a controller of my project:
`$cart = new Cart('cart', $cartSessionStore);`

This works, but it overwrites the cart with id 'cart' every time the page gets loaded.

I have tried using `SessionStore->get('cart')` but this only returns an array (not a cart object).

Thanks in advance,
Kevin

**Comment by mike182uk** [comment]
Hey @KevinSleegers,

The cart has a save and restore method, documented [here](https://github.com/mike182uk/cart#save--restore-cart-state)

So when you initialize the cart, straight afterwards you will want to call the restore method, then at the end of the lifecycle of your app, you will want to call the save method.

Hope this helps!

**Comment by KevinSleegers** [comment]
Thanks alot for your answer, it all makes sense now! 👍

**Comment by mike182uk** [comment]
Hey @KevinSleegers,

Looks like you found a bug! The cart would fail to restore if it had not been previously saved, which of course it wouldn't have if this was the first time the cart was being used.

I have made it so that if the saved cart is empty, it skips the restore checks.

You will need to update to `v2.2.3`.

Let me know if you have any problems 👍
